**a) Usage of methods such as floor(), ceil(), sqrt(), isqrt(), gcd() etc**

In [1]:
import math
print("math.floor(5.8):", math.floor(5.8))
print("math.ceil(5.2):", math.ceil(5.2))
print("math.sqrt(16):", math.sqrt(16))
print("math.isqrt(17):", math.isqrt(17))
print("math.gcd(48, 18):", math.gcd(48, 18))

math.floor(5.8): 5
math.ceil(5.2): 6
math.sqrt(16): 4.0
math.isqrt(17): 4
math.gcd(48, 18): 6


**b) Usage of attributes of array such as ndim, shape, size, methods such as sum(), mean(), sort(), sin() etc.**

In [2]:
import numpy as np
arr = np.array([[10, 70, 30], [50, 40, 60]])
print("Array:\n", arr)
print("Number of dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Sum of all elements:", arr.sum())
print("Mean of array:", arr.mean())
print("Sorted array:\n", np.sort(arr))
print("Sine of array elements:\n", np.sin(np.radians(arr)))

Array:
 [[10 70 30]
 [50 40 60]]
Number of dimensions: 2
Shape: (2, 3)
Size: 6
Sum of all elements: 260
Mean of array: 43.333333333333336
Sorted array:
 [[10 30 70]
 [40 50 60]]
Sine of array elements:
 [[0.17364818 0.93969262 0.5       ]
 [0.76604444 0.64278761 0.8660254 ]]


**c) Usage of methods such as det(), eig()**

In [3]:
import numpy as np
from numpy.linalg import det, eig
A = np.array([[4, 2],
              [3, 1]])
print("Matrix A:\n", A)
det_A = det(A)
print("Determinant of A:", det_A)
eigenvalues, eigenvectors = eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Matrix A:
 [[4 2]
 [3 1]]
Determinant of A: -2.0
Eigenvalues: [ 5.37228132 -0.37228132]
Eigenvectors:
 [[ 0.82456484 -0.41597356]
 [ 0.56576746  0.90937671]]


**d) Reshape a 1D List into 2D and 3D Arrays Using NumPy**

In [4]:
import numpy as np
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
array_1d = np.array(my_list)
print("1D array:", array_1d)
array_2d = array_1d.reshape(3, 4)
print("2D array:\n", array_2d)
array_3d = array_1d.reshape(2, 3, 2)
print("3D array:\n", array_3d)

1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3D array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**e) Generate Arrays and Matrices Using NumPy**

In [5]:
a = np.array([1, 2, 3])
print("Array from list:", a)
z = np.zeros((2, 3))
print("2x3 Zero matrix:\n", z)
o = np.ones((3, 3))
print("3x3 Ones matrix:\n", o)
r = np.arange(0, 10, 2)
print("Array with step of 2:", r)
l = np.linspace(0, 1, 5)
print("5 evenly spaced values between 0 and 1:", l)
I = np.eye(4)
print("4x4 Identity matrix:\n", I)
rand = np.random.rand(2, 3)
print("Random 2x3 matrix:\n", rand)
randint = np.random.randint(1, 10, size=(3, 3))
print("Random 3x3 integer matrix:\n", randint)

Array from list: [1 2 3]
2x3 Zero matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]
3x3 Ones matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array with step of 2: [0 2 4 6 8]
5 evenly spaced values between 0 and 1: [0.   0.25 0.5  0.75 1.  ]
4x4 Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random 2x3 matrix:
 [[0.62357421 0.46624061 0.61121547]
 [0.13112688 0.37726353 0.11538001]]
Random 3x3 integer matrix:
 [[7 9 8]
 [6 9 3]
 [1 2 8]]


**f) Find the Determinant of a Matrix using SciPy**

In [6]:
import numpy as np
from scipy.linalg import det
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
det_A = det(A)
print("Determinant of A:", det_A)

Determinant of A: -306.0


**g) Find Eigenvalues and Eigenvectors Using SciPy**

In [7]:
import numpy as np
from scipy.linalg import eig
A = np.array([[4, 2],
              [1, 3]])
eigenvalues, eigenvectors = eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [5.+0.j 2.+0.j]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
